

=pod

=head1 NAME

ur list - list objects, classes, modules



=head1 VERSION

This document describes ur list version 0.28.

=head1 SUB-COMMANDS

 classes  [CLASSES-OR-MODULES]  a command which operates on classes/modules in a UR 
                                 namespace directory                                
 modules  [CLASSES-OR-MODULES]  a command which operates on classes/modules in a UR 
                                 namespace directory                                
 objects  --subject-class-n...  lists objects matching specified params             




=cut

