requires 'Carp';
requires 'Class::AutoloadCAN', '0.03';
requires 'Class::Autouse', '2.0';
requires 'Clone::PP', '1.02';
requires 'DBD::SQLite', '1.14';
requires 'DBI', '1.601';
requires 'Data::Compare', '0.13';
requires 'Data::UUID', '0.148';
requires 'Date::Format';
requires 'Devel::GlobalDestruction';
requires 'File::Basename', '2.73';
requires 'File::Path';
requires 'File::Temp';
requires 'FreezeThaw', '0.43';
requires 'Getopt::Complete', '0.26';
requires 'JSON';
requires 'Lingua::EN::Inflect', '1.88';
requires 'List::MoreUtils';
requires 'MRO::Compat';
requires 'Path::Class';
requires 'Pod::Simple::HTML', '3.03';
requires 'Pod::Simple::Text', '2.02';
requires 'Sub::Install', '0.924';
requires 'Sub::Name', '0.04';
requires 'Sys::Hostname', '1.11';
requires 'Test::Fork';
requires 'Text::Diff', '0.35';
requires 'Text::Glob';
requires 'YAML';
requires 'perl', 'v5.8.7';
requires 'version';
